### ISSUE TITLE
Using tokenizers within threads is a little cumbersome

### ISSUE THREAD

**Issue by epwalsh** [guillaume-be/rust-tokenizers#39] opened 2020-10-13 18:02 UTC
Hey @guillaume-be, I'm having a little trouble using `rust-tokenizers` within a multi-process data loading pipeline. In particular, with the `RobertaTokenizer`, the issue is that it's not `Send` or `Sync` due to the use of `Rc` and `RefCell`, so currently what I have to do is instantiate the tokenizer within each worker thread after they have been spawned (see [here](https://github.com/allenai/rustberta-snli/blob/2c1c96bcd48ee734dbaa38ef6772232a0619fc70/src/data.rs#L168), for example).

This is a little cumbersome, and also isn't ideal because the [`cache`](https://github.com/guillaume-be/rust-tokenizers/blob/master/main/src/preprocessing/tokenizer/roberta_tokenizer.rs#L38) can't be shared between threads.

Is there any reason not to use something like a `RwLock` instead?

**Comment by guillaume-be** [comment] 2020-10-13 18:17
Hi @epwalsh ,

Thank you for raising this. I noticed the same while preparing the documentation for the crate (which was long overdue). In addition to a much cleaner API, I am working on making all tokenizers `Send` (which would by extension make all pipelines in `rust-bert` `Send`). 

My solution was to remove the shared `Rc` `vocab` element for tokenizers that are not compatible with multi-threading (remove the `Rc` altogether - was not adding much value anyway). The tokenizers relying on BPE (and cache) are not multi-threaded (as opposed to non-cached tokenizers such as wordpiece of sentencepiece) as the lock/unlock mechanism was causing a very large overhead due to the extremely frequent access, and causing it to be slower than without cache. 

I am almost done with the PR (a few more docstrings to write). Please check this out at https://github.com/guillaume-be/rust-tokenizers/tree/documentation. I am expecting to have this merged sometime tomorrow. The code is fully functional though - so feel free to have a look.

**Comment by epwalsh** [comment] 2020-10-13 18:33
Awesome! I'll take a look at that :)

**Comment by epwalsh** [comment] 2020-10-13 19:25
For BPE-type tokenizers, although they cannot be `Sync` due to the `RefCell` on the `cache`, it would be nice if they we're easily clone-able so you could at least `Send` clones across threads. Using the `from_existing_merges_and_vocab()` method as a crude way of cloning would suffice, but this is not possible right now since the `merges` field is private, unless I'm missing something.

**Comment by guillaume-be** [comment] 2020-10-13 19:50
@epwalsh I am not sure I understand. I just made a change so that BpePairVocab is now `Clone`.

The following is possible, not sure if it's what you meant?
```rust
let vocab = Gpt2Vocab::from_file(vocab_path.to_str().unwrap())?;
let merges = BpePairVocab::from_file(merges_path.to_str().unwrap())?;
let merges_clone = merges.clone();

let gpt2_tokenizer = Gpt2Tokenizer::from_existing_vocab_and_merges(vocab, merges_copy, false);
```

**Comment by epwalsh** [comment] 2020-10-13 21:30
I mean, if all we have is a `RobertaTokenizer`, and want to get another identical `RobertaTokenizer` without reading vocab and merges from file again, is there currently a way to do that?

I know we can recover the `RobertaVocab` from `tokenizer.vocab()`, but not the `BpePairVocab`.

**Comment by guillaume-be** [comment] 2020-10-14 15:37
@epwalsh I am actually updating all tokenizers to support multithreading. Using `RwLock` has negligible performance penalty compared to `RefCell`. I just implemented it for GPT2 and can observe very significant speed gains using multithreaded tokenization.

I will update the rest of the tokenizers today, and they should all be `Send` and `Sync`. I believe this should solve your issues.
Thanks a lot for the pointer!

**Comment by guillaume-be** [comment] 2020-10-14 16:06
I just opened a PR (https://github.com/guillaume-be/rust-tokenizers/pull/41)

@epwalsh all tokenizers now support multithreading - can you please give it a try and let me know if this solves your issue?

**Comment by epwalsh** [comment] 2020-10-14 16:24
Yay! I'll give it a try today soon

**Comment by epwalsh** [comment] 2020-10-14 17:07
I just confirmed it works! And sharing the tokenizer across threads actually led to a slight performance improvement over instantiating a separate tokenizer for each thread 🙂 I'm guessing the improvement was due to having a shared cache.

**Comment by guillaume-be** [comment] 2020-11-22 09:13
Closing as I assume the issue is solved

**Closed by guillaume-be** 2020-11-22 09:13 UTC
